### ISSUE TITLE
Gmail Connection problem

### ISSUE THREAD

**Issue by barilki** [Enough-Software/enough_mail#130]
I/flutter ( 7280): C: a39 ENABLE UTF8=ACCEPT
I/flutter ( 7280): S: * BYE Terminating connection. Please try again.
I/flutter ( 7280): C: untagged not handled: [* BYE Terminating connection. Please try again.
I/flutter ( 7280): ] by task null
I/flutter ( 7280): A: Done, connection closed
I/flutter ( 7280): A: reconnecting....
I/flutter ( 7280): A: trying to connect...
I/flutter ( 7280): A: connecting to server imap.gmail.com:993 - secure: true
I/flutter ( 7280): S: * ENABLED UTF8=ACCEPT
I/flutter ( 7280): S: a39 OK Success
I/flutter ( 7280): connected.
I/flutter ( 7280): A: re-select mailbox "INBOX".
I/flutter ( 7280): C: a40 SELECT INBOX
I/flutter ( 7280): S: * OK Gimap ready for requests from 217.175.89.30 i12mb162476734wrp

I am using version 0.3.0 of enough_mail. When using high-level API, login doesn't work. It shows that he is trying to connect too many times.
All email(Gmail) security permissions exist.

**Comment by robert-virkus** [comment]
Can you please post the initial sequence? From the snipped above I don't get an idea what is going wrong. Thanks in advance!

**Comment by robert-virkus** [comment]
I just tested gmail access, while I found a problem processing some fetch responses (compare #131), the login seemed to work fine. Please note that I am using an app password in my case, since I haven't registered with Gmail yet.
Compare https://support.google.com/accounts/answer/185833 for details about how to set up an app password.

**Comment by barilki** [comment]
Thank you!
