### ISSUE TITLE
IMAP: Session timeout

### ISSUE THREAD

**Issue by ali7234** [Enough-Software/enough_mail#50]
Facing an issue that, if not using app for 30 or maybe 60 minutes or app is in background for that specific time, After that, If I opened the app and by using the previous IMAP login and socket connection, call any IMAP function like fetchMessagesByCriteria() or other, they didn't response back or they give the SocketException. Currently, I am trying to resolve this issue with the **ImapClient.isLoggedIn**, but it didn't help to resolve this issue. Please guide how I resolve this issue.

**Log**

```
I/flutter (27861): C: a14 LIST "" *
I/flutter (27861): 56.0
I/flutter (27861): 56.0
I/flutter (27861): Error: SocketException: OS Error: Connection reset by peer, errno = 104, address = serverAddress, port = 53324
I/flutter (27861): Done, connection closed
E/flutter (27861):
```
**Note**
Already handled the Socket Exception, but trying to find out the workaround to check the socket connection and session and then call the IMAP functions.

**Comment by studiozocaro** [comment]
i'have same problem

**Comment by robert-virkus** [comment]
Have you registered for an `ImapConnectionLostEvent` or `ImapEvent` at the `ImapClient.eventBus`?

For example:
```dart
eventBus.on<ImapConnectionLostEvent>().listen((event) {
   //TODO trigger reconnect
});
```

**Comment by ali7234** [comment]
Do I need to run the idleStart() for ImapConnectionLostEvent?

**Comment by robert-virkus** [comment]
No, that should not be required.

**Comment by ali7234** [comment]
Implement the listener as suggested, but if I am not using the app for long time(>~20 min). After that If I call any of the IMAP function. Sometimes they give me the Socket Exception and sometimes they didn't response back as seen in the screenshot. And I noticed, if the server close the inactive session this listener not call.

**Screenshot**
![image](https://user-images.githubusercontent.com/23405583/81933219-77142300-9606-11ea-9812-46f3121eb5f8.png)

**Comment by ali7234** [comment]
I think the issue is somewhat related to this: https://github.com/dart-lang/web_socket_channel/issues/40

**Comment by robert-virkus** [comment]
The [IMAP IDLE RFC](https://tools.ietf.org/html/rfc2177) says this about long running sessions:

The server MAY consider a client inactive if it has an IDLE command
   running, and if such a server has an inactivity timeout it MAY log
   the client off implicitly at the end of its timeout period.  Because
   of that, clients using IDLE are advised to terminate the IDLE and
   re-issue it at least every 29 minutes to avoid being logged off.
   This still allows a client to receive immediate mailbox updates even
   though it need only "poll" at half hour intervals.

So maybe use a timer and repeat the idleDone() and idleStart() sequence every x minutes?

**Comment by robert-virkus** [comment]
Closing this for now. The high level API provides polling support that uses `IDLE` when available.
